Adding administrator registration functionality
SantiagoBedoyaU/SoftwareIIBackend pull request #8
Opened 2024-10-14 19:54 UTC by Esteban-Naranjo

It was modified the function "Create user" in order to used it in two cases, when is requested by a normal user and when is requested by an admin user.

2024-10-14 22:23 UTC, SantiagoBedoya requested changes
Please solve the comments.

2024-10-14 22:23 UTC, SantiagoBedoya commented on cmd/api/main.go
> +			}
We do not need to create a new route to create managers. It is a bad practice to use a handler for more than 1 route in the application. Please use the route on line 77 and delete these lines.

2024-10-14 22:23 UTC, SantiagoBedoya commented on internal/adapter/middleware/admin_middleware.go
I understood what you did, but we don't need this middleware.

2024-10-14 22:23 UTC, SantiagoBedoya commented on internal/adapter/middleware/auth_middleware.go
> +		ctx.Set("adminPermission", false)
We do not need `AdminMiddleware` to know if the role is Admin or not. Please take a look at line 33, we have userRole, we can simply validate if this value has the value of Admin Role.

2024-10-14 22:23 UTC, SantiagoBedoya commented on internal/core/service/auth_service.go
With the above comments, we do not need the `ValidateAdminRol` method.

2024-10-20 18:03 UTC, SantiagoBedoyaU approved these changes

2024-10-20 19:06 UTC, merged